[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle Auth0 callbacks and email confirmation links
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle client-side routing for Docusaurus
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
