[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle CMS admin redirects
[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Handle client-side routing for Docusaurus
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
