// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Docs sidebar
  docsSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      items: [{type: 'autogenerated', dirName: 'docs'}],
    },
  ],

  // Guidelines sidebar
  guidelinesSidebar: [
    {
      type: 'category', 
      label: 'Guidelines',
      items: [{type: 'autogenerated', dirName: 'guidelines'}],
    },
  ],

  // Planning sidebar
  planningSidebar: [
    {
      type: 'category',
      label: 'Planning',
      items: [
        {type: 'autogenerated', dirName: 'planning'},
        {
          type: 'category',
          label: 'User Stories',
          items: [{type: 'autogenerated', dirName: 'planning/user-stories'}],
        },
        {
          type: 'category',
          label: 'Issues',
          items: [{type: 'autogenerated', dirName: 'planning/issues'}],
        },
        {
          type: 'category',
          label: 'Sprints',
          items: [{type: 'autogenerated', dirName: 'planning/sprints'}],
        },
      ],
    },
  ],

  // Templates sidebar
  templatesSidebar: [
    {
      type: 'category',
      label: 'Templates',
      items: [{type: 'autogenerated', dirName: 'templates'}],
    },
  ],
};

export default sidebars;
